server:
  port: 8082

spring:
  application:
    name: microservice-aws

  aws:
    secret:
      key: ${AWS_SECRET_KEY}

    access:
      key: ${AWS_ACCESS_KEY}

    region:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



