server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-aws
          uri: http://localhost:8082
          predicates:
            - Path=/api/aws/**

        - id: msvc-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: msvc-inventory
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventory/**

        - id: msvc-notifications
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**

security:
  service:
    url: http://localhost:8081/api/auth

eureka:
  client:
    register-with-eureka: false
